onEvent('gamephases.initialize', event => {
    event.phase('bronze')
    .block('minecraft:copper_ore', 'minecraft:stone')
    .block('minecraft:deepslate_copper_ore', 'minecraft:deepslate')
    .block('immersiveengineering:ore_lead', 'minecraft:stone')
    .block('immersiveengineering:ore_silver', 'minecraft:stone')
    .block('electrodynamics:oretin', 'minecraft:stone')
    .block('electrodynamics:oresilver', 'minecraft:stone')
    .block('electrodynamics:orelead', 'minecraft:stone')
    .block('electrodynamics:deepslateoretin', 'minecraft:deepslate')
    .block('electrodynamics:deepslateoresilver', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorelead', 'minecraft:deepslate')
    .block('immersiveengineering:deepslate_ore_lead', 'minecraft:deepslate')
    .block('immersiveengineering:deepslate_ore_silver', 'minecraft:deepslate')
    event.phase('iron')
    .block('minecraft:iron_ore', 'minecraft:stone')
    .block('minecraft:deepslate_iron_ore', 'minecraft:deepslate')
    .block('minecraft:gold_ore', 'minecraft:stone')
    .block('minecraft:deepslate_gold_ore', 'minecraft:stone')
    .block('minecraft:lapis_ore', 'minecraft:stone')
    .block('minecraft:deepslate_lapis_ore', 'minecraft:deepslate')
    .block('minecraft:redstone_ore', 'minecraft:stone')
    event.phase('iron2')
    .block('immersiveengineering:ore_nickel', 'minecraft:stone')
    .block('create:zinc_ore', 'minecraft:stone')
    .block('create:deepslate_zinc_ore', 'minecraft:deepslate')
    .block('immersiveengineering:deepslate_ore_nickel', 'minecraft:deepslate')
    event.phase('enlightenment')
    .block('electrodynamics:oresulfur', 'minecraft:stone')
    .block('electrodynamics:oreniter', 'minecraft:stone')
    .block('electrodynamics:orehalite', 'minecraft:stone')
    .block('the_ages_of_times:manganese_dioxide_ore', 'minecraft:stone')
    .block('the_ages_of_times:stibarsen', 'minecraft:tuff')
    .block('electrodynamics:deepslateoresulfur', 'minecraft:deepslate')
    .block('electrodynamics:deepslateoreniter', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorehalite', 'minecraft:deepslate')
    .block('tconstruct:cobalt_ore', 'minecraft:stone')
    event.phase('industrial')
    .block('electrodynamics:orethorianite', 'minecraft:stone')
    .block('electrodynamics:oremonazite', 'minecraft:stone')
    .block('electrodynamics:orevanadinite', 'minecraft:stone')
    .block('electrodynamics:orealuminum', 'minecraft:stone')
    .block('electrodynamics:orechromite', 'minecraft:stone')
    .block('electrodynamics:orerutile', 'minecraft:stone')
    .block('minecraft:coal_ore', 'minecraft:stone')
    .block('minecraft:deepslate_coal_ore', 'minecraft:deepslate')
    .block('minecraft:redstone_ore', 'the_ages_of_times:cinnabar_ore')
    .block('minecraft:deepslate_redstone_ore', 'minecraft:deepslate')
    .block('minecraft:emerald_ore', 'minecraft:stone')
    .block('minecraft:deepslate_emerald_ore', 'minecraft:deepslate')
    .block('minecraft:diamond_ore', 'minecraft:stone')
    .block('minecraft:deepslate_diamond_ore', 'minecraft:deepslate')
    .block('immersiveengineering:ore_aluminum', 'minecraft:stone')
    .block('immersiveengineering:ore_uranium', 'minecraft:stone')
    .block('electrodynamics:oreuraninite', 'minecraft:stone')
    .block('the_ages_of_times:ore_wolframite', 'minecraft:stone')
    .block('the_ages_of_times:ore_argyrodite', 'minecraft:stone')
    .block('the_ages_of_times:ore_columbite', 'minecraft:stone')
    .block('the_ages_of_times:ore_sperrylite', 'minecraft:stone')
    .block('the_ages_of_times:ore_strontianite', 'minecraft:stone')
    .block('the_ages_of_times:ore_tantalite', 'minecraft:stone')
    .block('the_ages_of_times:ore_gadolinite', 'minecraft:stone')
    .block('the_ages_of_times:ore_zircon', 'minecraft:stone')
    .block('electrodynamics:orelepidolite', 'minecraft:stone')
    .block('electrodynamics:oremolybdenum', 'minecraft:stone')
    .block('electrodynamics:orefluorite', 'minecraft:stone')
    .block('electrodynamics:oresylvite', 'minecraft:stone')
    .block('the_ages_of_times:ore_borax', 'minecraft:stone')
    .block('electrodynamics:deepslateoreuraninite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorethorianite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateoremonazite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorevanadinite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorealuminum', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorechromite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorerutile', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorelepidolite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateoremolybdenum', 'minecraft:deepslate')
    .block('electrodynamics:deepslateorefluorite', 'minecraft:deepslate')
    .block('electrodynamics:deepslateoresylvite', 'minecraft:deepslate')
    .block('immersiveengineering:deepslate_ore_aluminum', 'minecraft:deepslate')
    .block('immersiveengineering:deepslate_ore_uranium', 'minecraft:deepslate')
    event.phase('future')
    .block('ae2:quartz_ore', 'minecraft:stone')
    .block('ae2:deepslate_quartz_ore', 'minecraft:deepslate')
    event.phase('orbit')
    .dimension('beyond_earth:earth_orbit')
    event.phase('moon')
    .dimension('beyond_earth:moon')
    .dimension('beyond_earth:moon_orbit')
    event.phase('solar')
    .dimension('beyond_earth:mars')
    .dimension('beyond_earth:mercury')
    .dimension('beyond_earth:venus')
    .dimension('beyond_earth:mars_orbit')
    .dimension('beyond_earth:mercury_orbit')
    .dimension('beyond_earth:venus_orbit')
    event.phase('outer')
    .dimension('beyond_earth:glacio')
    .dimension('beyond_earth:glacio_orbit')
    event.phase('never')
    .dimension('minecraft:the_nether')
    .dimension('minecraft:the_end')
})