onEvent('recipes', event => {
	// Unification des craft
	event.remove({ id: 'tconstruct:common/materials/copper_ingot_from_nuggets' })
	event.remove({ id: 'tconstruct:common/materials/copper_nugget_from_ingot' })
	event.remove({ id: 'create:crafting/materials/copper_nugget' })
	event.remove({ id: 'beyond_earth:steel_block' })
	event.remove({ id: 'beyond_earth:steel_ingot' })
	event.remove({ id: 'beyond_earth:steel_ingot_from_nugget' })
	event.remove({ id: 'beyond_earth:steel_nugget_from_ingot' })
	event.remove({ id: 'beyond_earth:steel_ingot_blasting' })
	event.remove({ id: 'immersiveengineering:crafting/nugget_copper_to_copper_ingot' })
	event.remove({ id: 'immersiveengineering:crafting/copper_ingot_to_nugget_copper' })
	event.remove({ id: 'immersiveengineering:crafting/ingot_lead_to_storage_lead' })
	event.remove({ id: 'immersiveengineering:crafting/storage_lead_from_slab' })
	event.remove({ id: 'immersiveengineering:crafting/storage_lead_to_ingot_lead' })
	event.remove({ id: 'immersiveengineering:crafting/storage_lead_to_slab' })
	event.remove({ id: 'immersiveengineering:crafting/raw_block_lead_to_raw_lead' })
	event.remove({ id: 'immersiveengineering:crafting/raw_lead_to_raw_block_lead' })
	event.remove({ id: 'immersiveengineering:crafting/nugget_silver_to_ingot_silver' })
	event.remove({ id: 'immersiveengineering:crafting/ingot_silver_to_nugget_silver' })
	event.remove({ id: 'immersiveengineering:crafting/ingot_silver_to_storage_silver' })
	event.remove({ id: 'immersiveengineering:crafting/storage_silver_to_ingot_silver' })
	event.remove({ id: 'immersiveengineering:crafting/storage_silver_to_slab' })
	event.remove({ id: 'immersiveengineering:crafting/storage_silver_from_slab' })
	event.remove({ id: 'immersiveengineering:crafting/raw_block_silver_to_raw_silver' })
	event.remove({ id: 'immersiveengineering:crafting/raw_silver_to_raw_block_silver' })
	event.remove({ id: 'immersiveengineering:crafting/ingot_aluminum_to_storage_aluminum' })
	event.remove({ id: 'immersiveengineering:crafting/storage_aluminum_to_ingot_aluminum' })
	event.remove({ id: 'immersiveengineering:crafting/storage_aluminum_from_slab' })
	event.remove({ id: 'immersiveengineering:crafting/storage_aluminum_to_slab' })
	event.remove({ id: 'immersiveengineering:crafting/ingot_steel_to_nugget_steel'})
	event.remove({ id: 'immersiveengineering:crafting/ingot_steel_to_storage_steel'})
	event.remove({ id: 'immersiveengineering:crafting/storage_steel_from_slab' })
	event.remove({ id: 'immersiveengineering:crafting/storage_steel_to_ingot_steel'})
	event.remove({ id: 'immersiveengineering:crafting/nugget_steel_to_ingot_steel'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_lead_from_dust_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_lead_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/copper_ingot_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/copper_ingot_from_dust_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_lead_from_blasting3'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_lead3'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_silver_from_dust_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_silver_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_silver_from_blasting3'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_silver3'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum2'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum3'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum_from_blasting2'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_aluminum_from_blasting3'})
	event.remove({ id: 'immersiveengineering:smelting/gold_ingot_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/gold_ingot_from_dust_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/iron_ingot_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/iron_ingot_from_dust_from_blasting'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_steel_from_dust'})
	event.remove({ id: 'immersiveengineering:smelting/ingot_steel_from_dust_from_blasting'})
	event.remove({ id: 'alchemistry:copper_ingot_from_blasting_copper_dust'})
	event.remove({ id: 'alchemistry:copper_ingot_from_smelting_copper_dust'})
	event.remove({ id: 'alchemistry:iron_ingot_from_smelting_iron_dust'})
	event.remove({ id: 'alchemistry:iron_ingot_from_blasting_iron_dust'})
	event.remove({ id: 'alchemistry:gold_ingot_from_smelting_gold_dust'})
	event.remove({ id: 'alchemistry:gold_ingot_from_blasting_gold_dust'})
	event.remove({ id: 'chemlib:tin_ingot_from_blasting_tin_dust'})
	event.remove({ id: 'chemlib:tin_ingot_from_smelting_tin_dust'})
	event.remove({ id: 'chemlib:lead_ingot_from_blasting_lead_dust'})
	event.remove({ id: 'chemlib:lead_ingot_from_smelting_lead_dust'})
	event.remove({ id: 'chemlib:silver_ingot_from_smelting_silver_dust'})
	event.remove({ id: 'chemlib:silver_ingot_from_blasting_silver_dust'})
	event.remove({ id: 'chemlib:aluminum_ingot_from_smelting_aluminum_dust'})
	event.remove({ id: 'chemlib:aluminum_ingot_from_blasting_aluminum_dust'})
	event.remove({ id: 'chemlib:nickel_ingot_from_smelting_nickel_dust'})
	event.remove({ id: 'chemlib:nickel_ingot_from_blasting_nickel_dust'})
	event.remove({ id: 'chemlib:molybdenum_ingot_from_smelting_molybdenum_dust'})
	event.remove({ id: 'chemlib:molybdenum_ingot_from_blasting_molybdenum_dust'})
	event.remove({ id: 'chemlib:lithium_ingot_from_smelting_lithium_dust'})
	event.remove({ id: 'chemlib:lithium_ingot_from_blasting_lithium_dust'})
	event.remove({ id: 'chemlib:vanadium_ingot_from_smelting_vanadium_dust'})
	event.remove({ id: 'chemlib:vanadium_ingot_from_blasting_vanadium_dust'})
	event.remove({ id: 'chemlib:tin_ingot_to_nugget'})
	event.remove({ id: 'chemlib:tin_nugget_to_ingot'})
	event.remove({ id: 'chemlib:tin_block_to_ingot'})
	event.remove({ id: 'chemlib:tin_ingot_to_block'})
	event.remove({ id: 'chemlib:lead_ingot_to_block'})
	event.remove({ id: 'chemlib:lead_block_to_ingot'})
	event.remove({ id: 'chemlib:lead_ingot_to_nugget'})
	event.remove({ id: 'chemlib:lead_nugget_to_ingot'})
	event.remove({ id: 'chemlib:silver_ingot_to_block'})
	event.remove({ id: 'chemlib:silver_block_to_ingot'})
	event.remove({ id: 'chemlib:silver_nugget_to_ingot'})
	event.remove({ id: 'chemlib:silver_ingot_to_nugget'})
	event.remove({ id: 'chemlib:aluminum_ingot_to_nugget'})
	event.remove({ id: 'chemlib:aluminum_nugget_to_ingot'})
	event.remove({ id: 'chemlib:aluminum_ingot_to_block'})
	event.remove({ id: 'chemlib:aluminum_block_to_ingot'})
	event.remove({ id: 'chemlib:nickel_ingot_to_nugget'})
	event.remove({ id: 'chemlib:nickel_nugget_to_ingot'})
	event.remove({ id: 'chemlib:nickel_ingot_to_block'})
	event.remove({ id: 'chemlib:nickel_block_to_ingot'})
	event.remove({ id: 'chemlib:zinc_nugget_to_ingot'})
	event.remove({ id: 'chemlib:zinc_ingot_to_nugget'})
	event.remove({ id: 'chemlib:zinc_ingot_to_block'})
	event.remove({ id: 'chemlib:zinc_block_to_ingot'})
	event.remove({ id: 'chemlib:cobalt_ingot_to_nugget'})
	event.remove({ id: 'chemlib:cobalt_nugget_to_ingot'})
	event.remove({ id: 'chemlib:cobalt_ingot_to_block'})
	event.remove({ id: 'chemlib:cobalt_block_to_ingot'})
	event.remove({ id: 'chemlib:titanium_ingot_to_block'})
	event.remove({ id: 'chemlib:titanium_block_to_ingot'})
	event.remove({ id: 'chemlib:chromium_ingot_to_block'})
	event.remove({ id: 'chemlib:chromium_block_to_ingot'})
})

onEvent('item.tags', event => {
	// Ajout de Tags
	event.get('forge:wires/copper').add('electrodynamics:wirecopper')
	event.get('immersiveengineering:circuits/solder').add('electrodynamics:wirecopper')

	// Retiré les Tags
	//Cuivre
	event.get('forge:nuggets/copper').remove(['immersiveengineering:nugget_copper', 'tconstruct:copper_nugget', 'create:copper_nugget'])
	event.get('forge:dusts/copper').remove(['chemlib:copper_dust', 'immersiveengineering:dust_copper'])
	event.get('forge:wires/copper').remove(['immersiveengineering:wire_copper', 'createaddition:copper_wire'])
	event.get('immersiveengineering:circuits/solder').remove(['immersiveengineering:wire_copper', 'createaddition:copper_wire'])
	event.get('forge:plates/copper').remove('chemlib:copper_plate')

	//Tin
	event.get('forge:nuggets/tin').remove('chemlib:tin_nugget')
	event.get('forge:ingots/tin').remove('chemlib:tin_ingot')
	event.get('forge:dusts/tin').remove('chemlib:tin_dust')
	event.get('forge:storage_blocks/tin').remove('chemlib:tin_metal_block')

	//Aluminium
	event.get('forge:dusts/aluminum').remove('chemlib:aluminum_dust')
	event.get('forge:nuggets/aluminum').remove('chemlib:aluminum_nugget')
	event.get('forge:plates/aluminum').remove(['immersiveengineering:plate_aluminum', 'chemlib:aluminum_plate'])
	event.get('forge:storage_blocks/aluminum').remove(['immersiveengineering:storage_aluminum', 'chemlib:aluminum_metal_block'])
	event.get('forge:ingots/aluminum').remove(['chemlib:aluminum_ingot', 'immersiveengineering:ingot_aluminum'])

	//Lead
	event.get('forge:nuggets/lead').remove('chemlib:lead_nugget')
	event.get('forge:raw_materials/lead').remove('immersiveengineering:raw_lead')
	event.get('forge:storage_blocks/lead').remove(['immersiveengineering:storage_lead', 'chemlib:lead_metal_block'])
	event.get('forge:dusts/lead').remove(['immersiveengineering:dust_lead', 'chemlib:lead_dust'])
	event.get('forge:plates/lead').remove(['chemlib:lead_plate', 'immersiveengineering:plate_lead'])
	event.get('forge:ingots/lead').remove(['immersiveengineering:ingot_lead', 'chemlib:lead_ingot'])

	//Silver
	event.get('forge:ingots/silver').remove(['immersiveengineering:ingot_silver', 'chemlib:silver_ingot'])
	event.get('forge:nuggets/silver').remove(['chemlib:silver_nugget', 'immersiveengineering:nugget_silver'])
	event.get('forge:plates/silver').remove('chemlib:silver_plate')
	event.get('forge:dusts/silver').remove(['immersiveengineering:dust_silver', 'chemlib:silver_dust'])
	event.get('forge:storage_blocks/silver').remove(['immersiveengineering:storage_silver', 'chemlib:silver_metal_block'])
	event.get('forge:raw_materials/silver').remove('immersiveengineering:raw_silver')

	//Nickel
	event.get('forge:ingots/nickel').remove('chemlib:nickel_ingot')
	event.get('forge:nuggets/nickel').remove('chemlib:nickel_nugget')
	event.get('forge:plates/nickel').remove('chemlib:nickel_plate')
	event.get('forge:dusts/nickel').remove('chemlib:nickel_dust')
	event.get('forge:storage_blocks/nickel').remove('chemlib:nickel_metal_block')

	//Steel
	event.get('forge:nuggets/steel').remove(['immersiveengineering:nugget_steel', 'beyond_earth:steel_nugget'])
	event.get('forge:ingots/steel').remove(['immersiveengineering:ingot_steel', 'beyond_earth:steel_ingot'])
	event.get('forge:dusts/steel').remove('immersiveengineering:dust_steel')
	event.get('forge:plates/steel').remove('immersiveengineering:plate_steel')
	event.get('forge:storage_blocks/steel').remove(['beyond_earth:steel_block', 'immersiveengineering:storage_steel'])

	//Zinc
	event.get('forge:ingots/zinc').remove('chemlib:zinc_ingot')
	event.get('forge:storage_blocks/zinc').remove('chemlib:zinc_metal_block')
	event.get('forge:nuggets/zinc').remove('chemlib:zinc_nugget')

	//Cobalt
	event.get('forge:nuggets/cobalt').remove('chemlib:cobalt_nugget')
	event.get('forge:storage_blocks/cobalt').remove('chemlib:cobalt_metal_block')
	event.get('forge:ingots/cobalt').remove('chemlib:cobalt_ingot')
	
	//Fer
	event.get('forge:plates/iron').remove(['immersiveengineering:plate_iron', 'chemlib:iron_plate'])
	event.get('forge:dusts/iron').remove(['chemlib:iron_dust', 'immersiveengineering:dust_iron'])

	//Or
	event.get('forge:plates/gold').remove(['chemlib:gold_plate', 'immersiveengineering:plate_gold'])
	event.get('forge:dusts/gold').remove(['chemlib:gold_dust', 'immersiveengineering:dust_gold'])

	//Molybdène
	event.get('forge:ingots/molybdenum').remove('chemlib:molybdenum_ingot')
	event.get('forge:dusts/molybdenum').remove('chemlib:molybdenum_dust')
	
	//Lithium
	event.get('forge:plates/lithium').remove('chemlib:lithium_plate')
	event.get('forge:dusts/lithium').remove('chemlib:lithium_dust')
	event.get('forge:ingots/lithium').remove('chemlib:lithium_ingot')

	//Vanadium
	event.get('forge:ingots/vanadium').remove('chemlib:vanadium_ingot')
	event.get('forge:dusts/vanadium').remove('chemlib:vanadium_dust')

	//Titanium
	event.get('forge:ingots/titanium').remove('chemlib:titanium_ingot')
	event.get('forge:plates/titanium').remove('chemlib:titanium_plate')
	event.get('forge:storage_blocks/titanium').remove('chemlib:titanium_metal_block')

	//Chromium
	event.get('forge:ingots/chromium').remove('chemlib:chromium_ingot')
	event.get('forge:storage_blocks/chromium').remove('chemlib:chromium_metal_block')
})