// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('jei.information', event=> {
	event.add('minecraft:leather', ['Use a ceramic shears on a leather tanner with a tanned hide'])
	event.add('the_ages_of_times:gold_water', ['Hit a Villager, Wandering Trader, Illusioner, Pillager, Evoker or Vindicator with a Beaker to obtains'])
})

onEvent('jei.hide.items', event => {
	// Unification
	event.hide(['chemlib:tin_metal_block', 'immersiveengineering:nugget_copper', 'create:copper_nugget', 'tconstruct:copper_nugget', 'chemlib:tin_nugget', 'immersiveengineering:dust_copper', 'chemlib:copper_dust', 'chemlib:tin_dust', 'immersiveengineering:wire_copper', 'createaddition:copper_wire', 'chemlib:copper_plate', 'chemlib:tin_ingot', 'immersiveengineering:storage_aluminum', 'chemlib:aluminum_dust', 'chemlib:aluminum_metal_block', 'immersiveengineering:storage_lead', 'chemlib:lead_dust', 'chemlib:lead_metal_block', 'immersiveengineering:ingot_aluminum', 'chemlib:aluminum_ingot', 'chemlib:gold_plate', 'immersiveengineering:plate_gold', 'immersiveengineering:ingot_lead', 'immersiveengineering:raw_lead', 'chemlib:lead_ingot', 'chemlib:aluminum_nugget', 'chemlib:gold_dust', 'immersiveengineering:dust_gold', 'immersiveengineering:plate_lead', 'chemlib:lead_nugget', 'immersiveengineering:plate_aluminum', 'chemlib:aluminum_plate', 'immersiveengineering:dust_lead', 'chemlib:lead_plate', 'immersiveengineering:storage_silver', 'chemlib:silver_metal_block', 'chemlib:titanium_metal_block', 'chemlib:nickel_dust', 'chemlib:nickel_metal_block', 'immersiveengineering:nugget_steel', 'chemlib:iron_dust', 'chemlib:zinc_ingot', 'immersiveengineering:ingot_silver', 'immersiveengineering:raw_silver', 'chemlib:titanium_plate', 'chemlib:nickel_ingot', 'beyond_earth:steel_nugget', 'immersiveengineering:plate_steel', 'chemlib:cobalt_nugget', 'immersiveengineering:dust_iron', 'chemlib:iron_plate', 'immersiveengineering:nugget_silver', 'chemlib:silver_plate', 'chemlib:silver_ingot', 'chemlib:nickel_nugget', 'beyond_earth:steel_ingot', 'immersiveengineering:dust_steel', 'chemlib:cobalt_ingot', 'immersiveengineering:plate_iron', 'chemlib:zinc_metal_block', 'immersiveengineering:dust_silver', 'chemlib:silver_dust', 'chemlib:silver_nugget', 'chemlib:nickel_plate', 'beyond_earth:steel_block', 'immersiveengineering:ingot_steel', 'chemlib:cobalt_metal_block', 'chemlib:zinc_nugget', 'chemlib:titanium_ingot', 'chemlib:molybdenum_ingot', 'chemlib:vanadium_dust', 'chemlib:lithium_dust', 'chemlib:chromium_ingot', 'chemlib:lithium_plate', 'chemlib:chromium_metal_block', 'chemlib:lithium_ingot', 'chemlib:molybdenum_dust', 'chemlib:vanadium_ingot'])
	event.hide(['immersiveengineering:dust_sulfur', 'chemlib:sulfur_dust', 'immersiveengineering:dust_saltpeter', 'butchersdelight:item_salt', 'createaddition:gold_wire', 'createaddition:electrum_ingot', 'createaddition:electrum_nugget', 'createaddition:electrum_sheet', 'createaddition:electrum_wire', 'magistuarmory:steel_ingot', 'magistuarmory:steel_nugget', 'magistuarmory:steel_plate', 'immersiveengineering:stick_steel', 'immersiveengineering:stick_iron', 'createaddition:iron_rod', 'car:iron_stick', 'chemlib:zinc_plate', 'createaddition:iron_wire'])
})

onEvent('jei.hide.fluids', event => {
	event.hide('beyond_earth:flowing_fuel')
	event.hide('beyond_earth:flowing_molten_calorite')
	event.hide('beyond_earth:flowing_molten_desh')
	event.hide('beyond_earth:flowing_molten_ostrum')
	event.hide('beyond_earth:flowing_oil')
	event.hide('beyond_earth:fuel')
	event.hide('beyond_earth:molten_calorite')
	event.hide('beyond_earth:molten_desh')
	event.hide('beyond_earth:molten_ostrum')
	event.hide('beyond_earth:oil')
	event.hide('car:bio_diesel')
	event.hide('car:methanol')
	event.hide('car:methanol_flowing')
	event.hide('create:chocolate')
	event.hide('create:flowing_chocolate')
	event.hide('create:flowing_honey')
	event.hide('create:flowing_tea')
	event.hide('create:honey')
	event.hide('create:tea')
	event.hide('createaddition:bioethanol')
	event.hide('createaddition:flowing_bioethanol')
	event.hide('createaddition:flowing_seed_oil')
	event.hide('createaddition:seed_oil')
	event.hide('immersiveengineering:acetaldehyde')
	event.hide('immersiveengineering:biodiesel')
	event.hide('immersiveengineering:concrete')
	event.hide('immersiveengineering:creosote')
	event.hide('immersiveengineering:ethanol')
	event.hide('immersiveengineering:herbicide')
	event.hide('immersiveengineering:phenolic_resin')
	event.hide('immersiveengineering:plantoil')
	event.hide('immersiveengineering:potion')
	event.hide('immersiveengineering:redstone_acid')
	event.hide('immersivepetroleum:benzene')
	event.hide('immersivepetroleum:crudeoil')
	event.hide('immersivepetroleum:diesel')
	event.hide('immersivepetroleum:diesel_sulfur')
	event.hide('immersivepetroleum:ethylene')
	event.hide('immersivepetroleum:gasoline')
	event.hide('immersivepetroleum:gasoline_additives')
	event.hide('immersivepetroleum:kerosene')
	event.hide('immersivepetroleum:lubricant')
	event.hide('immersivepetroleum:lubricant_cracked')
	event.hide('immersivepetroleum:napalm')
	event.hide('immersivepetroleum:naphtha')
	event.hide('immersivepetroleum:naphtha_cracked')
	event.hide('immersivepetroleum:propylene')
	event.hide('minecraft:flowing_lava')
	event.hide('minecraft:flowing_milk')
	event.hide('minecraft:flowing_water')
	event.hide('minecraft:lava')
	event.hide('minecraft:milk')
	event.hide('minecraft:water')
	event.hide('pneumaticcraft:biodiesel')
	event.hide('pneumaticcraft:diesel')
	event.hide('pneumaticcraft:etching_acid')
	event.hide('pneumaticcraft:ethanol')
	event.hide('pneumaticcraft:gasoline')
	event.hide('pneumaticcraft:kerosene')
	event.hide('pneumaticcraft:lpg')
	event.hide('pneumaticcraft:lubricant')
	event.hide('pneumaticcraft:memory_essence')
	event.hide('pneumaticcraft:oil')
	event.hide('pneumaticcraft:plastic')
	event.hide('pneumaticcraft:vegetable_oil')
	event.hide('pneumaticcraft:yeast_culture')
	event.hide('sliceanddice:fertilizer')
	event.hide('sliceanddice:flowing_fertilizer')
	event.hide('tconstruct:beetroot_soup')
	event.hide('tconstruct:blazing_blood')
	event.hide('tconstruct:blood')
	event.hide('tconstruct:earth_slime')
	event.hide('tconstruct:flowing_beetroot_soup')
	event.hide('tconstruct:flowing_blazing_blood')
	event.hide('tconstruct:flowing_blood')
	event.hide('tconstruct:flowing_earth_slime')
	event.hide('tconstruct:flowing_honey')
	event.hide('tconstruct:flowing_liquid_soul')
	event.hide('tconstruct:flowing_magma')
	event.hide('tconstruct:flowing_molten_aluminum')
	event.hide('tconstruct:flowing_molten_amethyst')
	event.hide('tconstruct:flowing_molten_amethyst_bronze')
	event.hide('tconstruct:flowing_molten_brass')
	event.hide('tconstruct:flowing_molten_bronze')
	event.hide('tconstruct:flowing_molten_clay')
	event.hide('tconstruct:flowing_molten_cobalt')
	event.hide('tconstruct:flowing_molten_constantan')
	event.hide('tconstruct:flowing_molten_copper')
	event.hide('tconstruct:flowing_molten_debris')
	event.hide('tconstruct:flowing_molten_diamond')
	event.hide('tconstruct:flowing_molten_electrum')
	event.hide('tconstruct:flowing_molten_emerald')
	event.hide('tconstruct:flowing_molten_ender')
	event.hide('tconstruct:flowing_molten_enderium')
	event.hide('tconstruct:flowing_molten_glass')
	event.hide('tconstruct:flowing_molten_gold')
	event.hide('tconstruct:flowing_molten_hepatizon')
	event.hide('tconstruct:flowing_molten_invar')
	event.hide('tconstruct:flowing_molten_iron')
	event.hide('tconstruct:flowing_molten_knightslime')
	event.hide('tconstruct:flowing_molten_lead')
	event.hide('tconstruct:flowing_molten_lumium')
	event.hide('tconstruct:flowing_molten_manyullyn')
	event.hide('tconstruct:flowing_molten_netherite')
	event.hide('tconstruct:flowing_molten_nickel')
	event.hide('tconstruct:flowing_molten_obsidian')
	event.hide('tconstruct:flowing_molten_osmium')
	event.hide('tconstruct:flowing_molten_pewter')
	event.hide('tconstruct:flowing_molten_pig_iron')
	event.hide('tconstruct:flowing_molten_platinum')
	event.hide('tconstruct:flowing_molten_porcelain')
	event.hide('tconstruct:flowing_molten_quartz')
	event.hide('tconstruct:flowing_molten_queens_slime')
	event.hide('tconstruct:flowing_molten_refined_glowstone')
	event.hide('tconstruct:flowing_molten_refined_obsidian')
	event.hide('tconstruct:flowing_molten_rose_gold')
	event.hide('tconstruct:flowing_molten_signalum')
	event.hide('tconstruct:flowing_molten_silver')
	event.hide('tconstruct:flowing_molten_slimesteel')
	event.hide('tconstruct:flowing_molten_soulsteel')
	event.hide('tconstruct:flowing_molten_steel')
	event.hide('tconstruct:flowing_molten_tin')
	event.hide('tconstruct:flowing_molten_tungsten')
	event.hide('tconstruct:flowing_molten_uranium')
	event.hide('tconstruct:flowing_molten_zinc')
	event.hide('tconstruct:flowing_mushroom_stew')
	event.hide('tconstruct:flowing_rabbit_stew')
	event.hide('tconstruct:flowing_scorched_stone')
	event.hide('tconstruct:flowing_seared_stone')
	event.hide('tconstruct:flowing_sky_slime')
	event.hide('tconstruct:flowing_venom')
	event.hide('tconstruct:honey')
	event.hide('tconstruct:liquid_soul')
	event.hide('tconstruct:magma')
	event.hide('tconstruct:molten_aluminum')
	event.hide('tconstruct:molten_amethyst')
	event.hide('tconstruct:molten_amethyst_bronze')
	event.hide('tconstruct:molten_brass')
	event.hide('tconstruct:molten_bronze')
	event.hide('tconstruct:molten_clay')
	event.hide('tconstruct:molten_cobalt')
	event.hide('tconstruct:molten_constantan')
	event.hide('tconstruct:molten_copper')
	event.hide('tconstruct:molten_debris')
	event.hide('tconstruct:molten_diamond')
	event.hide('tconstruct:molten_electrum')
	event.hide('tconstruct:molten_emerald')
	event.hide('tconstruct:molten_ender')
	event.hide('tconstruct:molten_enderium')
	event.hide('tconstruct:molten_glass')
	event.hide('tconstruct:molten_gold')
	event.hide('tconstruct:molten_hepatizon')
	event.hide('tconstruct:molten_invar')
	event.hide('tconstruct:molten_iron')
	event.hide('tconstruct:molten_knightslime')
	event.hide('tconstruct:molten_lead')
	event.hide('tconstruct:molten_lumium')
	event.hide('tconstruct:molten_manyullyn')
	event.hide('tconstruct:molten_netherite')
	event.hide('tconstruct:molten_nickel')
	event.hide('tconstruct:molten_obsidian')
	event.hide('tconstruct:molten_osmium')
	event.hide('tconstruct:molten_pewter')
	event.hide('tconstruct:molten_pig_iron')
	event.hide('tconstruct:molten_platinum')
	event.hide('tconstruct:molten_porcelain')
	event.hide('tconstruct:molten_quartz')
	event.hide('tconstruct:molten_queens_slime')
	event.hide('tconstruct:molten_refined_glowstone')
	event.hide('tconstruct:molten_refined_obsidian')
	event.hide('tconstruct:molten_rose_gold')
	event.hide('tconstruct:molten_signalum')
	event.hide('tconstruct:molten_silver')
	event.hide('tconstruct:molten_slimesteel')
	event.hide('tconstruct:molten_soulsteel')
	event.hide('tconstruct:molten_steel')
	event.hide('tconstruct:molten_tin')
	event.hide('tconstruct:molten_tungsten')
	event.hide('tconstruct:molten_uranium')
	event.hide('tconstruct:molten_zinc')
	event.hide('tconstruct:mushroom_stew')
	event.hide('tconstruct:potion')
	event.hide('tconstruct:rabbit_stew')
	event.hide('tconstruct:scorched_stone')
	event.hide('tconstruct:seared_stone')
	event.hide('tconstruct:sky_slime')
	event.hide('tconstruct:venom')
	event.hide('the_ages_of_times:antimatter')
	event.hide('the_ages_of_times:darkmatter')
	event.hide('the_ages_of_times:flowing_antimatter')
	event.hide('the_ages_of_times:flowing_darkmatter')
	event.hide('the_ages_of_times:flowing_hydrogen_oxygen_mix')
	event.hide('the_ages_of_times:hydrogen_oxygen_mix')
  })

onEvent('jei.add.items', event => {
	//Papyrus
	event.add('atum:papyrus_plant')
})

//Tooltips ChemLib
onEvent('item.tooltip', tooltip => {

	function chemLib(name, text1, text2) {
		tooltip.addAdvanced(['#forge:ingots/' + name, '#forge:nuggets/' + name, '#forge:dusts/' + name, '#forge:plates/' + name, '#forge:storage_blocks/' + name], (item, advanced, text) => {
			text.add(1, Text.of('§3' + text1))
			text.add(2, Text.of('§7' + text2))
		})
	}
	chemLib('silver', 'Ag (47)', 'Transition Metals')
	chemLib('nickel', 'Ni (28)', 'Transition Metals')
	//chemLib('osmium', 'Os (76)', 'Transition Metals')
	chemLib('aluminum', 'Al (13)', 'Post-Transition Metals')
	chemLib('lead', 'Pb (82)', 'Post-Transition Metals')
	//chemLib('tin', 'Sn (50)', 'Post-Transition Metals')
	//chemLib('uranium', 'U (92)', 'Actinides')
	chemLib('iron', 'Fe (26)', 'Transition Metals')
	chemLib('gold', 'Au (79)', 'Transition Metals')
	chemLib('copper', 'Cu (29)', 'Transition Metals')
	chemLib('sulfur', 'S (16)', 'Reactive Non-Metals')
	//chemLib('cobalt', 'Co (27)', 'Transition Metals')

	function chemLibCompounds(item, text1){
		tooltip.addAdvanced(item, (item, advanced, text) => {
			text.add(1, Text.of(text1))
		})
	}

	chemLibCompounds(['the_ages_of_times:iron_oxide_iii'], '§3Fe₃O₄')
	chemLibCompounds(['the_ages_of_times:manganese_chloride_ii'], '§3MnCl₂')
	chemLibCompounds(['the_ages_of_times:nitrogen'], '§3N₂')
	chemLibCompounds(['the_ages_of_times:oxygen_ballon'], '§3O₂')
	chemLibCompounds(['the_ages_of_times:sodium_aluminate'], '§3NaAlO₂')
	chemLibCompounds(['the_ages_of_times:sodium_sulfide'], '§3Na₂S')
	chemLibCompounds(['the_ages_of_times:sodium_chromate'], '§3Na₂CrO₄')
	chemLibCompounds(['the_ages_of_times:sodium_dichromate'], '§3Na₂Cr₂O₇')
	chemLibCompounds(['the_ages_of_times:titanium_tetrachloride'], '§3TiCl₄')
	chemLibCompounds(['the_ages_of_times:tungstic_acid'], '§3H₂WO₄')
	chemLibCompounds(['the_ages_of_times:iron_chloride'], '§3FeCl₂')
	chemLibCompounds(['the_ages_of_times:mercury_oxide'], '§3HgO')
	chemLibCompounds(['the_ages_of_times:potassium_bisulfate'], '§3KHSO₄')
	chemLibCompounds(['the_ages_of_times:silicon_tetrafluoride'], '§3SiF₄')
	chemLibCompounds(['the_ages_of_times:potassium_fluoride'], '§3KF')
	chemLibCompounds(['the_ages_of_times:diethyl_ether'], '§3C₄H₁₀O')
	chemLibCompounds(['the_ages_of_times:yttrium_oxide'], '§3Y₂O₃')
	chemLibCompounds(['the_ages_of_times:terbium_oxide'], '§3Tb₄O₇')
	chemLibCompounds(['the_ages_of_times:erbium_oxide'], '§3Er₂O₃')
	chemLibCompounds(['the_ages_of_times:ytterbium_oxide'], '§3Yb₂O₃')
	chemLibCompounds(['the_ages_of_times:cerium_oxide'], '§3CeO₂')
	chemLibCompounds(['the_ages_of_times:praseodymium_oxide'], '§3Pr₂O₃')
	chemLibCompounds(['the_ages_of_times:neodymium_oxide'], '§3Nd₂O₃')
	chemLibCompounds(['the_ages_of_times:holmium_oxide'], '§3Ho₂O₃')
	chemLibCompounds(['the_ages_of_times:dysprosium_oxide'], '§3Dy₂O₃')
	chemLibCompounds(['the_ages_of_times:dysprosium_chloride'], '§3DyCl₃')
	chemLibCompounds(['the_ages_of_times:dysprosium_hydroxide'], '§3Dy(OH)₃')
	chemLibCompounds(['the_ages_of_times:magnesium_oxide'], '§3MgO')
	chemLibCompounds(['the_ages_of_times:chloroplatinic_acid'], '§3H₂PtCl₆')
	chemLibCompounds(['the_ages_of_times:cadmium_oxide'], '§3CdO')
	chemLibCompounds(['the_ages_of_times:boric_acid'], '§3H₃BO₃')
	chemLibCompounds(['the_ages_of_times:vivianite_dust'], '§3Fe₃(PO₄)₂•8(H₂O)')
	chemLibCompounds(['the_ages_of_times:gold_water', 'the_ages_of_times:golden_water_bucket'], '§3H₈₈O₂₉N₄₃C₂₅K₆Cl₆S₂NaCaMg')

	function chemLibElement(item, text1, text2) {
	tooltip.addAdvanced(item, (item, advanced, text) => {
		text.add(1, Text.of(text1))
		text.add(2, Text.of(text2))
	})}

	chemLibElement(['electrodynamics:dustlithium', 'electrodynamics:platelithium', 'electrodynamics:ingotlithium'], '§3Li (3)', '§7Alkali Metals')
	chemLibElement(['#forge:ingots/titanium', '#forge:storage_blocks/titanium', '#forge:plates/titanium'], '§3Ti (22)', '§7Transition Metals')
	chemLibElement(['electrodynamics:ingotchromium', 'electrodynamics:resourceblockchromium'], '§3Cr (24)', '§7Transition Metals')
	chemLibElement(['electrodynamics:ingotmolybdenum', 'electrodynamics:dustmolybdenum'], '§3Mo (42)', '§7Transition Metals')
	chemLibElement(['electrodynamics:dustvanadium', 'electrodynamics:ingotvanadium'], '§3V (23)', '§7Transition Metals')
	chemLibElement(['#forge:ingots/tin', '#forge:nuggets/tin', '#forge:dusts/tin', '#forge:storage_blocks/tin'], '§3Sn (50)', '§7Post-Transition Metals')
	chemLibElement(['#forge:ingots/cobalt', '#forge:nuggets/cobalt', '#forge:storage_blocks/cobalt'], '§3Co (27)', '§7Transition Metals')
	chemLibElement(['create:zinc_ingot', 'create:zinc_nugget', 'createaddition:zinc_sheet', 'create:zinc_block'], '§3Zn (30)', '§7Transition Metals')
	chemLibElement(['nuclearscience:thorianitedust'], '§3Th (90)', '§7Actinides')

	// Others Tooltips
	tooltip.addAdvanced(['the_ages_of_times:andesite_shaft'], (item, advanced, text) => {
		text.add(1, Text.of('Just for crafting'))
	})

})