
#Toutes les configurations liées à la base du jeu
[gameplay]
	#Nombre de citoyens initiaux. [Defaut: 4, min: 1, max: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#Le ruban de construction doit-il être placé autour des bâtiments en construction ? [Defaut: true]
	builderplaceconstructiontape = true
	#Les joueurs peuvent-ils placer une quantité infinie de camps/navires de ravitaillement ? [Defaut: false]
	allowinfinitesupplychests = false
	#Les joueurs peuvent-ils abandonner leur colonie pour en créer une nouvelle facilement ? Remarque : c'est buggé! [Defaut: false]
	allowinfinitecolonies = false
	#Est-ce que les colonies dans les autres dimensions sont autorisées ? [Defaut: true]
	allowotherdimcolonies = true
	#Si une colonie est sous le nombre initial de citoyens, cela modifie le délai avant l'apparition d'un nouveau citoyen. [Defaut: 60, min: 10, max: 600]
	#Range: 10 ~ 600
	citizenrespawninterval = 60
	#Nombre max de citoyens dans une colonie. [Defaut: 250, min: 4, max: 500]
	#Range: 4 ~ 500
	maxcitizenpercolony = 250
	#Délai après chaque placement de bloc (augmenter ceci augmente le délai). [Defaut: 15, min: 1, max: 500]
	#Range: 1 ~ 500
	builderbuildblockdelay = 15
	#Modificateur de délai pour miner un bloc (diminuer ceci réduira le délai). [Defaut: 500, min: 1, max: 10000]
	#Range: 1 ~ 10000
	blockminingdelaymodifier = 500
	#Les fonctionnalités en développement doivent-elles êtres activées (peut être buggé)? [Defaut: false]
	enableindevelopmentfeatures = false
	#Les noms des citoyens doivent-ils être affichés ? [Defaut: true]
	alwaysrendernametag = true
	#Les travailleurs doivent-ils travailler sous la pluie? [Defaut: false]
	workersalwaysworkinrain = false
	#Les utilisateurs doivent-ils envoyer des notifications en rejoignant/quittant une colonie ? [Defaut: true]
	sendenteringleavingmessages = true
	#Les joueurs sont-ils autorisés à changer les noms de citoyens? -1 pour faux, 0 pour certains joueurs uniquement, 1 pour vrai. (Pour définir quels joueurs peuvent modifier les noms, consultez la section «Groupe d'autorisations spéciales» ci-dessous.) [Defaut: 1, min: -1, max: 1]
	#Range: -1 ~ 1
	allowglobalnamechanges = 1
	#Le contenu des vacances doit-il être affiché? [Defaut: true]
	holidayfeatures = true
	#Quantité de terre par compost rempli. [Defaut: 1, min: 0, max: 100]
	#Range: 0 ~ 100
	dirtfromcompost = 1
	#Chance que le Mineur obtienne un minerai en minant de la pierre (par défaut, il peut être étendu avec des datapacks à d'autres matériaux). C'est un pourcentage. (Pour changer quels minerais le Mineur peut trouver, regardez "Liste des Minerais Chanceux".) [Defaut: 1, min: 0, max: 100]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#Le niveau minimum qu'un hôtel de ville doit avoir pour permettre la téléportation vers les colonies alliées. [Defaut: 3, min: 0, max: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Suggérer l'utilisation de l'outil de construction quand on place un bâtiment sans l'outil. [Defaut: true]
	suggestbuildtoolplacement = true
	#Modificateur de la consommation alimentaire. [Defaut: 1.000000, min: 0.100000, max: 100.000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#A quel point les maladies sont courantes. 1 = Très commun, 100 = Extrêmement rare. [Defaut: 5, min: 1, max: 100]
	#Range: 1 ~ 100
	diseasemodifier = 5
	#Si une partie de la colonie est chargée par un propriétaire/agent, la colonie doit-elle rester chargée ? (Définissez le nombre de morceaux à charger avec l'option "Colony Chunk Loading Strictness") [Defaut: false]
	forceloadcolony = false
	#Cela contrôle combien de chunks sont chargés avec l'option "Chunk Load Colony". Plus la valeur est élevée, moins de chunks seront chargés. (Les chunks centraux seront chargés en premier.) 1 = charge de tous les chunks visités. [Defaut: 3, min: 1, max: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#Chance d'obtenir un visiteur maléfique de taverne qui s'enfuira avec les ressources que vous lui donnez. C'est un %. [Defaut: 2, min: 1, max: 100]
	#Range: 1 ~ 100
	badvisitorchance = 2
	#Le nombre maximum de bûches d'un arbre pour le Forestier à vérifier pendant la recherche de son arbre. [Defaut: 400, min: 1, max: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#Désactive les restrictions de placement des camps d'approvisionnement, pour les skyworld et similaire [Defaut: false]
	nosupplyplacementrestrictions = false
	#Les attaquants apparaitront dans le ciel si activé [Defaut: false]
	skyraiders = false

#Toutes les configurations liées au système de requête
[research]
	#Permet l'achèvement automatique et (presque) instantané des recherches pour les joueurs en mode créatif. Si elle est fausse, les joueurs en mode créatif pourront toujours commencer des recherches, mais auront des taux de progression normaux. [Defaut: true]
	researchcreativecompletion = true
	#Augmente significativement la quantité d'information relative aux datapacks de recherches loggée pendant le chargement d'un monde. [Defaut: false]
	researchdebuglog = false
	#Une liste d'éléments à facturer aux joueurs lorsqu'ils annulent une recherche déjà effectuée. 
	researchresetcost = ["minecolonies:ancienttome:1"]

#Toutes les configurations liées aux commandes Minecolonies
[commands]
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc rtp? [Defaut: false]
	canplayerusertpcommand = false
	#Est-ce que les joueurs devraient être autorisés à utiliser la commande "/mc colony teleport" ? [Defaut: false]
	canplayerusecolonytpcommand = false
	#Les joueurs peuvent-ils se téléporter vers les colonies alliées ? [Defaut: true]
	canplayeruseallytownhallteleport = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande "/mc maison"? Remarque: Seul le propriétaire de la colonie peut utiliser cette commande. [Defaut: false]
	canplayerusehometpcommand = false
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc colony info ? [Defaut: true]
	canplayeruseshowcolonyinfocommand = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc citizens kill ? [Defaut: false]
	canplayerusekillcitizenscommand = false
	#Les joueurs doivent-ils être autorisés à utiliser la commande /mc colony addOfficer ? [Defaut: true]
	canplayeruseaddofficercommand = true
	#Les joueurs devraient-ils être autorisés à utiliser la commande /mc colony delete ? [Defaut: true]
	canplayerusedeletecolonycommand = true
	#Nombre de tentatives pour trouver une téléportation aléatoire sûre (avec /mc rtp). [Defaut: 4, min: 1, max: 10]
	#Range: 1 ~ 10
	numberofattemptsforsafetp = 4

#Toutes les configurations liées à la taille d’une colonie
[claims]
	#Distance de réclamation maximale pour une colonie. C'est le rayon, mesuré en chunks. [Defaut: 20, min: 1, max: 50]
	#Range: 1 ~ 50
	maxColonySize = 20
	#La distance minimale (en chunks) entre les colonies. [Defaut: 8, min: 1, max: 200]
	#Range: 1 ~ 200
	minColonyDistance = 8
	#Taille initiale de la revendication pour une colonie. C'est le rayon, mesuré en chunks. [Defaut: 4, min: 1, max: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#La distance minimum/maximum des apparitions doit-elle également affecter le placement des colonies ? [Defaut: false]
	restrictcolonyplacement = false
	#Distance maximale (en blocs) des apparitions des colonies dans le monde. [Defaut: 8000, min: 1000, max: 100000]
	#Range: 1000 ~ 100000
	maxdistancefromworldspawn = 8000
	#Distance minimale (en blocs) des apparitions des colonies dans le monde. [Defaut: 512, min: 1, max: 1000]
	#Range: 1 ~ 1000
	mindistancefromworldspawn = 512
	#Les officiers d'une colonie doivent-ils recevoir les progrès de cette colonie ? [Defaut: true]
	officersreceiveadvancements = true

#Toutes les configurations liées aux éléments de combat de MineColonies
[combat]
	#Faut-il ou non faire apparaître des pillards. [Defaut: true]
	dobarbariansspawn = true
	#Le paramètre de difficulté pour les invasions. [Defaut: 5, min: 0, max: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#La taille maximale d'une horde de pillards. [Defaut: 80, min: 6, max: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 80
	#Si les pilleurs peuvent ou non franchir les obstacles [Defaut: true]
	dobarbariansbreakthroughwalls = true
	#Le nombre moyen de nuits entre les raids. [Defaut: 14, min: 1, max: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#Le nombre minimum de nuits entre les raids. [Defaut: 10, min: 1, max: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#Les monstres devraient-ils attaquer les citoyens? [Defaut: true]
	mobattackcitizens = true
	#Si les pilleurs peuvent ou non casser les portes. [Defaut: true]
	shouldraiderbreakdoors = true
	#Est-ce que les citoyens devraient appeler des gardes pour se faire aider lorsque des attaques ? [Defaut: true]
	citizencallforhelp = true
	#Multiplicateur des dégâts pour les Gardes Archers. [Defaut: 1.000000, min: 0.100000, max: 5.000000]
	#Range: 0.1 ~ 5.0
	rangerdamagemult = 1.0
	#Multiplicateur des dégâts pour les Gardes Chevaliers. [Defaut: 1.000000, min: 0.100000, max: 5.000000]
	#Range: 0.1 ~ 5.0
	knightdamagemult = 1.0
	#Multiplicateur de santé pour tous les gardes. [Defaut: 1.000000, min: 0.100000, max: 5.000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Activez le mode PVP de MineColonies (les colonies peuvent être détruites et anéanties dans certaines conditions). [Defaut: false]
	pvp_mode = false
	#Jours avant que les bateaux pirates ne disparaissent. [Defaut: 3, min: 1, max: 10]
	#Range: 1 ~ 10
	daysuntilpirateshipsdespawn = 3
	#Niveau maximum Y (hauteur) pour que les pillards apparaissent. [Defaut: 200, min: 1, max: 500]
	#Range: 1 ~ 500
	maxyforbarbarians = 200

#Toutes les options de configuration de permissions
[permissions]
	#La protection des colonies doit-elle être activée ? [Defaut: true]
	enablecolonyprotection = true
	#Détermine le nombre max de sauvegardes gardées [Defaut: 50, min: 3, max: 5000]
	#Range: 3 ~ 5000
	maxkeptbackups = 50
	#Indépendamment de la protection de la colonie, les explosions doivent-elles être enlevées à l'intérieur des colonies ? DAMAGE_NOTHING prévient de toutes les explosions. DAMAGES_PLAYERS, autorise les explosions à faire des dégâts aux joueurs et aux créatures agressives, mais pas aux blocs, ni aux créatures neutres et amicales. DAMAGES_ENTITIES autorise les dégâts à toutes les entités. DAMAGE_EVERYTHING autorise les explosions aux entités et aux blocs. 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#Les joueurs qui ont des autorisations spéciales, notamment pour changer les noms des citoyens (voir «Changements de nom» ci-dessus). 
	specialpermgroup = ["_Raycoms_"]
	#Les blocs avec lesquels les joueurs devraient pouvoir interagir dans n'importe quelle colonie (ex: distributeurs automatiques) 
	freetointeractblocks = ["dirt", "0 0 0"]
	#Secondes entre chaque message d'autorisation (pour réduire le spam). [Defaut: 30, min: 1, max: 1000]
	#Range: 1 ~ 1000
	secondsBetweenPermissionMessages = 30

#Toutes les configurations liées à la compatibilité entre mods
[compatibility]
	#Items consommés par les citoyens dans la Bibliothèque. 
	configliststudyitems = ["minecraft:paper;400;100", "minecraft:book;600;10"]
	#Items requis par les visiteurs de la Taverne. 
	configlistrecruitmentitems = ["minecraft:hay_block;3", "minecraft:book;2", "minecraft:enchanted_book;9", "minecraft:diamond;9", "minecraft:emerald;8", "minecraft:baked_potato;1", "minecraft:gold_ingot;2", "minecraft:redstone;2", "minecraft:lapis_lazuli;2", "minecraft:cake;11", "minecraft:sunflower;5", "minecraft:honeycomb;6", "minecraft:quartz;3"]
	#Liste des blocs rarement trouvés par magie par les Mineurs (voir "Chance des Minerais"). Inclus le bloc et sa chance, séparés par des points d’exclamation. 
	luckyores = ["minecraft:coal_ore!64", "minecraft:copper_ore!48", "minecraft:iron_ore!32", "minecraft:gold_ore!16", "minecraft:redstone_ore!8", "minecraft:lapis_ore!4", "minecraft:diamond_ore!2", "minecraft:emerald_ore!1"]
	#Taille du tronc des récoltes forestière pour les arbres dynamiques: 1-8. [Defaut: 5, min: 1, max: 8]
	#Range: 1 ~ 8
	dynamictreeharvestsize = 5
	#Compensation pour la durabilité maximale de la canne à pêche non enchantée qu'une cabane de pêche T2 peut utiliser, par rapport à d'autres outils en fer (250). Le Fer de Thermal Foundation nécessite +6. Les huttes T3 peuvent utiliser des cannes à pêche de n'importe quelle durabilité, tant qu'elles peuvent subit des dommages. En dessous de -250, seules les cannes à pêche vanilla sont autorisées, exceptées celles de T1. [Defaut: 6, min: -249, max: 250000]
	#Range: -249 ~ 250000
	fishingroddurabilityadjustt2 = 6
	#Compensation pour la durabilité maximale de la canne à pêche non enchantée qu'une cabane de pêche T1 peut utiliser, par rapport à d'autres outils en bois (59).  Les cannes à pêche vanilla fonctionnent toujours, mais des équivalents nécessiteraient +6.  La valeur par défaut permet d'aller jusqu'à l'Argent de Thermal Foundation.  En dessous de -59, seules les cannes à pêche vanilla sont autorisées. [Defaut: 22, min: -58, max: 250000]
	#Range: -58 ~ 250000
	fishingroddurabilityadjustt1 = 22
	#Toutes les maladies que les citoyens peuvent attraper. Leurs noms, leurs fréquences et les ingrédients pour les soigner. 
	diseases = ["Influenza,100,minecraft:carrot,minecraft:potato", "Measles,10,minecraft:dandelion,minecraft:kelp,minecraft:poppy", "Smallpox,1,minecraft:honey_bottle,minecraft:golden_apple"]
	#Au chargement des recettes, un fichier d'audit CSV se génère pour vous aider à déboguer les datapacks ou autres mods. [Defaut: false]
	auditcraftingtags = false
	#Active le débogage de l'inventaire. [Defaut: false]
	debuginventories = false

#Toutes les configurations liées au pathfinding
[pathfinding]
	#Détail des messages de débogage du Pathfinding. [Defaut: 0, min: 0, max: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Nombre minimum de rails consécutifs pour que les citoyens puissent les utiliser. [Defaut: 8, min: 5, max: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#Nombre de processus additionnels à utiliser pour le Pathfinding. [Defaut: 2, min: 1, max: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#Toutes les configurations liées au système de requête
[requestSystem]
	#Est-ce que le système de requête doit montrer les informations de debug dans le debug.info? Utile en cas de dysfonctionnement. [Defaut: false]
	enabledebuglogging = false
	#Nombre maximal d'essais que le système de requête effectuera pour les requêtes réessayables. Une valeur plus élevée augmente la charge du serveur. [Defaut: 3, min: 1, max: 10]
	#Range: 1 ~ 10
	maximalretries = 3
	#Nombre de tiques entre les tentatives du système de requête pour les requêtes réessayables. Une baisse augmente la charge du serveur. [Defaut: 1200, min: 30, max: 10000]
	#Range: 30 ~ 10000
	delaybetweenretries = 1200
	#Est-ce que le système de requête doit résoudre créativement (si possible) quand le joueur est demandé à résoudre une requête ? C'est un outil de débogage et cela peut prendre très longtemps avant de résoudre la requête. [Defaut: false]
	creativeresolve = false
	#Les joueurs doivent-ils être autorisés à utiliser la commande /mc colony requestsystem-reset ? [Defaut: false]
	canplayeruseresetcommand = false

