import mods.orestages.OreStages;

OreStages.addOreStage("bronze", <blockstate:minecraft:copper_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:minecraft:deepslate_copper_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("bronze", <blockstate:immersiveengineering:ore_lead>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:immersiveengineering:ore_silver>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:oretin>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:oresilver>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:orelead>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:deepslateoretin>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:deepslateoresilver>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("bronze", <blockstate:electrodynamics:deepslateorelead>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("bronze", <blockstate:immersiveengineering:deepslate_ore_lead>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("bronze", <blockstate:immersiveengineering:deepslate_ore_silver>, <blockstate:minecraft:deepslate>, true);

OreStages.addOreStage("iron", <blockstate:minecraft:iron_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:deepslate_iron_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:gold_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:deepslate_gold_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:lapis_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:deepslate_lapis_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("iron", <blockstate:minecraft:redstone_ore>, <blockstate:minecraft:stone>, true);

OreStages.addOreStage("iron2", <blockstate:immersiveengineering:ore_nickel>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron2", <blockstate:create:zinc_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("iron2", <blockstate:create:deepslate_zinc_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("iron2", <blockstate:immersiveengineering:deepslate_ore_nickel>, <blockstate:minecraft:deepslate>, true);

OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:oresulfur>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:oreniter>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:orehalite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("enlightenment", <blockstate:the_ages_of_times:manganese_dioxide_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("enlightenment", <blockstate:the_ages_of_times:stibarsen>, <blockstate:minecraft:tuff>, true);
OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:deepslateoresulfur>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:deepslateoreniter>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("enlightenment", <blockstate:electrodynamics:deepslateorehalite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("enlightenment", <blockstate:tconstruct:cobalt_ore>, <blockstate:minecraft:stone>, true);

OreStages.addOreStage("industrial", <blockstate:electrodynamics:orethorianite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:oremonazite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orevanadinite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orealuminum>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orechromite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orerutile>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:coal_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:deepslate_coal_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:redstone_ore>, <blockstate:the_ages_of_times:cinnabar_ore>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:deepslate_redstone_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:emerald_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:deepslate_emerald_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:diamond_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:minecraft:deepslate_diamond_ore>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:immersiveengineering:ore_aluminum>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:immersiveengineering:ore_uranium>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:oreuraninite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_wolframite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_argyrodite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_columbite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_sperrylite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_strontianite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_tantalite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_gadolinite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_zircon>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orelepidolite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:oremolybdenum>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:orefluorite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:oresylvite>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:the_ages_of_times:ore_borax>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateoreuraninite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorethorianite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateoremonazite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorevanadinite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorealuminum>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorechromite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorerutile>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorelepidolite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateoremolybdenum>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateorefluorite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:electrodynamics:deepslateoresylvite>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:immersiveengineering:deepslate_ore_aluminum>, <blockstate:minecraft:deepslate>, true);
OreStages.addOreStage("industrial", <blockstate:immersiveengineering:deepslate_ore_uranium>, <blockstate:minecraft:deepslate>, true);

OreStages.addOreStage("future", <blockstate:ae2:quartz_ore>, <blockstate:minecraft:stone>, true);
OreStages.addOreStage("future", <blockstate:ae2:deepslate_quartz_ore>, <blockstate:minecraft:deepslate>, true);

mods.MobStages.addStage("iron", "atum:assassin");
mods.MobStages.addStage("iron", "atum:bandit_warlord");
mods.MobStages.addStage("iron", "atum:barbarian");
mods.MobStages.addStage("iron", "atum:brigand");
mods.MobStages.addStage("iron", "atum:nomad");
mods.MobStages.addStage("iron", "atum:sergeant");
mods.MobStages.addStage("iron", "minecraft:wandering_trader");
mods.MobStages.addStage("iron", "minecraft:evoker");
mods.MobStages.addStage("iron", "minecraft:pillager");
mods.MobStages.addStage("iron", "minecraft:vindicator");

mods.MobStages.addReplacement("atum:assassin", "minecraft:bat");
mods.MobStages.addReplacement("atum:bandit_warlord", "minecraft:bat");
mods.MobStages.addReplacement("atum:barbarian", "minecraft:bat");
mods.MobStages.addReplacement("atum:brigand", "minecraft:bat");
mods.MobStages.addReplacement("atum:nomad", "minecraft:bat");
mods.MobStages.addReplacement("atum:sergeant", "minecraft:bat");
mods.MobStages.addReplacement("minecraft:wandering_trader", "minecraft:bat");
mods.MobStages.addReplacement("minecraft:evoker", "minecraft:bat");
mods.MobStages.addReplacement("minecraft:pillager", "minecraft:bat");
mods.MobStages.addReplacement("minecraft:vindicator", "minecraft:bat");

mods.MobStages.addStage("never", "minecraft:iron_golem");
mods.MobStages.addReplacement("minecraft:iron_golem", "minecraft:bat");